source 'https://rubygems.org'

gem 'rails', '3.2.3'

gem 'sqlite3'

gem "webrat", ">= 0.7.2.beta.1"

group :development, :test do 
  gem 'rspec-rails' 
  gem 'factory_girl_rails' 
end 

group :test do 
  gem 'faker' 
  gem 'capybara', "2.0.3"
  gem 'guard-rspec' 
  gem 'launchy' 
end

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'
